### PR TITLE
refactor: use md in links

### PR DESCRIPTION
**Pull request by ouuan**
In this way, the links are not only available on the Hugo site, but also available on GitHub, at local, etc.

However, this is only available for the links in the Markdown files, not for those in the HTML files.

There are many links to update, so any help is welcome.

### CODE REVIEW

**Comment by ouuan** [comment]
@StudyingFather If you have time, you can help do this refactor first.

**Comment by coder3101** [comment]
The only downside of this refactoring is that it opens the possibility of cross-language linking. If the links are not correctly updated for each language, there are chances that a Russian translation could point to English translation.

Is there a way to exclude the language part?

Like `[<something>](../path/_index.md#foobar)` instead of `[<something>](../path/_index.zh.md#foobar)`

**Comment by ouuan** [comment]
> Is there a way to exclude the language part?
> 
> Like `[<something>](../path/_index.md#foobar)` instead of `[<something>](../path/_index.zh.md#foobar)`

The motivation is to link to the files so that the links are available not only on the website but also in the Markdown files themselves. So it's meaningless if we exclude the language codes.

**Comment by StudyingFather** [comment]
All links are updated now and this pr is ready for review.

But there is a problem that when the link contain space (like `Code Edit`), it can't render properly. So some help is needed to solve it.

**Comment by ouuan** [comment]
> All links are updated now and this pr is ready for review.
> 
> But there is a problem that when the link contains space (like `Code Edit`), it can't render properly. So some help is needed to solve it.

We can rename the directories to the names in the URLs.

**Comment by StudyingFather** [comment]
@ouuan Now all directories have been renamed and links have been updated now.

Maybe it's time to review the changes.

**Review by ouuan — COMMENTED** [review]
LGTM!

**Review by StudyingFather — APPROVED** [review]

**Pull request merged**
