### PR TITLE
Add page "Why CP Editor?"

### PR DESCRIPTION
**Pull request by Ravenclaw-OIer**
Created Why CP Editor

I'll continue to complete the actual documentation for features.

### CODE REVIEW

**Comment by ouuan** [comment]
I didn't expect revert commits in the new PR... Are you not familiar with git? You can `git reset --hard hugo` and `git push --force-with-lease`.

**Comment by Ravenclaw-OIer** [comment]
Yep, I only made it half way through the git documentation...... :cry:

**Comment by ouuan** [comment]
You can [enable GitHub Actions in your fork](https://github.com/Ravenclaw-OIer/cpeditor.github.io/actions) to get the Markdown files automatically formatted.

**Comment by ouuan** [comment]
> through the git documentation

Are you reading the documentation? I'd suggest [Learn Git Branching](https://learngitbranching.js.org/).

**Comment by Ravenclaw-OIer** [comment]
Thanks! I really think that the documentation is a little bit complicated for complete newbies like me... Will read it, thank you!

**Pull request closed without merging**
