### PR TITLE
Add support for Palestine and remove testimonials

### PR DESCRIPTION
**Pull request by coder3101**
This PR adds following changes to homepage and navbar.
- Remove testimonials as this is no longer required.
- Add a nav icon to show support for Palestine.

### CODE REVIEW

**Comment by coder3101** [comment]
@ouuan Please Approve the PR.

**Comment by ouuan** [comment]
I'm not sure if it is proper to simply add this icon on the CP Editor website.

I have not learned about every detail of the war, but AFAIK, I think that it is not that simple to just support one of the two countries. It is not that one of them is absolutely correct and the other one is absolutely wrong. I believe that the goal is to achieve peace and protect civilians.

This logo is too simple to approach the correct conclusion, and I doubt if it is actually beneficial for the people in Palestine and Israel.

**Comment by coder3101** [comment]
> I have not learned about every detail of the war, but AFAIK, I think that it is not that simple to just support one of the two countries. It is not that one of them is absolutely correct and the other one is absolutely wrong.

It is advisable to delve into the comprehensive history of both countries, extending beyond the events of 7th October, to gain deeper insights into discerning which side might be facing oppression. As responsible citizens, advocating for peace, freedom, justice, and opposing oppression is paramount.

To clarify, this effort is not intended to express support for war but rather advocates for the establishment of a free Palestinian state, seen as the long-term solution to the conflict. Therefore, logo "Free Palestine."


> I'm not sure if it is proper to simply add this icon on the CP Editor website.

I am open to any professional suggestions that you believe would be appropriate.

**Comment by ouuan** [comment]
Maybe you can show your support elsewhere? The CP Editor website does receive much traffic which is appealing, but I think other places are more suitable to express your support for Palestine. Not a professional suggestion though.

**Comment by xamir82** [comment]
"Please add support for antisemitic Islamists who have no regard for the values I claim to hold, as a way of performing a useless, pseudo-moralistic gesture."

**Comment by coder3101** [comment]
@xamir82 violated the code of conduct governing this project, quoted below.

> We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

**Comment by ouuan** [comment]
> @xamir82 violated the code of conduct governing this project, quoted below.

> @cpeditor blocked [xamir82](https://github.com/xamir82)

I suggest that this is a "use of inappropriate language" instead of a "serious violation of community standards, including sustained inappropriate behavior". The consequence should be at most a warning instead of instant banning.

**Comment by coder3101** [comment]
I'll close it off.😤

**Pull request closed without merging**
