### PR TITLE
fix: use remote branches in the build script

### PR DESCRIPTION
**Pull request by ouuan**

### CODE REVIEW

**Review by coder3101 — APPROVED** [review]

**Comment by ouuan** [comment]
Now Render is not configured correctly :thinking:

**Comment by ouuan** [comment]
I'm not sure why, but https://cpeditor-github-io-pr-64.onrender.com/v6.6 is 404 now.

**Comment by ouuan** [comment]
I don't know why. We can ignore Render and merge to test if it's fine on GitHub Pages.

**Comment by coder3101** [comment]
Can you just clear me this new changes. PR on which branches will fail render?

**Comment by ouuan** [comment]
> PR on which branches will fail render?

I think all branches are the same. None fails, but the version pages are 404 not found.

**Comment by ouuan** [comment]
And it's not this PR that makes Render fail.

**Comment by ouuan** [comment]
If we can't fix it, we can stop using the script on Render.

**Review by coder3101 — APPROVED** [review]

**Comment by ouuan** [comment]
It works: https://cpeditor.org/v6.6/

**Pull request merged**
