### PR TITLE
fix: update security settings naming for macOS

### PR DESCRIPTION
**Pull request by jackhallam**

### CODE REVIEW

**Comment by ouuan** [comment]
@coder3101 What was your macOS version on which the setting was "Settings -> Security -> General"?

@jackhallam What about yours? What's your macOS version :thinking:

**Comment by ouuan** [comment]
@allcontributors add @jackhallam as a contributor for reporting bugs and writing content.

**Comment by jackhallam** [comment]
> @jackhallam What about yours? What's your macOS version 🤔

macOS Big Sur 11.4

**Comment by coder3101** [comment]
> @coder3101 What was your macOS version on which the setting was "Settings -> Security -> General"?

It was old macOS Catalina. We added dmg support very back, they have changed the names now but I didn't change because this action is done by most mac Users on daily basis. Even installing vscode they have to do it.

**Review by coder3101 — APPROVED** [review]

**Review by swift-zym — APPROVED** [review]

**Review by ouuan — APPROVED** [review]

**Pull request merged**
