### PR TITLE
docs(Fakevim): Add Vim docs and tips

### PR DESCRIPTION
**Pull request by coder3101**
The PR adds documentation for following things:
Inside Code Editing
- Vim Emulation
- Enable current line highlighting

In addition to these It add Detailed table of supported vim commands in General and some Vim tips in Tips section. 
It also renames, the `code-edit` to `code-editing`

### CODE REVIEW

**Comment by coder3101** [comment]
@StudyingFather please translate this PR to keep Chinese translations up to date.

**Comment by coder3101** [comment]
@ouuan Please review this PR.

**Comment by ouuan** [comment]
I think it's fine to put Vim Commands in preferences/code-editing.

**Comment by coder3101** [comment]
> I think it's fine to put Vim Commands in preferences/code-editing.

Sure, we can move it inside Enable Vim Emulation Settings.

**Comment by asharkhan3101** [comment]
Superseded by #324

**Pull request closed without merging**
