### PR TITLE
docs: Add information about cursor width

### PR DESCRIPTION
**Pull request by sonulohani**
Linked to: https://github.com/cpeditor/cpeditor/pull/795

### CODE REVIEW

**Review by coder3101 — COMMENTED** [review]
Looks good, but @StudyingFather or @ChungZH could you please add this to Chinese translation.

**Review by coder3101 — APPROVED** [review]

**Comment by ouuan** [comment]
The zh version shouldn't be updated. Otherwise, it won't be marked as unfinished.

**Comment by coder3101** [comment]
> The zh version shouldn't be updated. Otherwise, it won't be marked as unfinished.

Do we find it updated or not based on commit history?

**Comment by ouuan** [comment]
> Do we find it updated or not based on commit history?

Based on page title, update time, and the "translated" param.

Translated or not:

-   If the "translated" is set, it is used.
-   Otherwise, we check whether the page title is the same as the English version.

If it's translated, we use the last updated time to check whether it's updated or not.

**Pull request merged**
